{
 "title": "Apache Logs Dashboard",
 "tags": [
  "honeypot",
  "apache",
  "logs"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_LOKI", "label": "Loki datasource", "query": "loki" },
   { "name": "ip_mask_regex", "label": "IP mask regex", "query": "(\\d+\\.\\d+)\\.\\d+\\.\\d+" },
   { "name": "ip_mask_replace", "label": "IP mask replace", "query": "$1.x.x" }
  ]
 },
 "panels": [
  {
   "title": "HTTP Requests",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"apache\"}\n| regexp `(?P<IP>\\d+\\.\\d+\\.\\d+\\.\\d+) - - \\[[^\\]]+\\] \"(?P<method>[A-Z]+) (?P<path>[^\"]+) HTTP/[0-9.]+\" (?P<code>\\d{3})`\n"
    }
   ]
  },
  {
   "title": "Top 10 IPs by Connections",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "topk(10, sum by (remote_ip) (count_over_time({job=\"apache\",type=\"access\"}[5m])))"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate({job=\"apache\",type=\"access\"}[1m])"
    }
   ]
  },
  {
   "title": "Heatmap de Status Codes por Método (últimas 4h)",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "count_over_time({job=\"apache\"} | regexp `(?P<method>[A-Z]+) [^\\\"]+ HTTP/[0-9.]+\" (?P<code>\\d{3})` [15m])",
     "legendFormat": "{{method}}_{{code}}"
    }
   ]
  }
 ]
}