{
 "title": "MySQL Logs Dashboard",
 "tags": [
  "honeypot",
  "mysql",
  "logs"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_LOKI", "label": "Loki datasource", "query": "loki" },
   { "name": "ip_mask_regex", "label": "IP mask regex", "query": "(\\d+\\.\\d+)\\.\\d+\\.\\d+" },
   { "name": "ip_mask_replace", "label": "IP mask replace", "query": "$1.x.x" }
  ]
 },
 "panels": [
  {
   "title": "Intentos de Login",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"apache\", type=\"error\"} |= \"[HONEYX]\" | regexp `\\[HONEYX\\] IP=(?P<ip>[^\\s]+) - Intento de login con usuario='(?P<username>.*?)' y (contrasena|contraseñ)='(?P<password>.*?)'`"
    }
   ]
  },
  {
   "title": "Top 10 IPs logins",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, sum by (ip) (count_over_time({job=\"apache\", type=\"error\"} |= \"[HONEYX]\" | regexp \"\\\\[HONEYX\\\\] IP=(?P<ip>[^\\\\s]+)\" [5m])))"
    }
   ]
  },
  {
   "title": "Consultas SELECT",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"mysql\",type=\"general\"} |~ \"Query\\\\s+SELECT\"\n| regexp `^(?P<ts>\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d+Z)\\s+(?P<thread>\\d+)\\s+Query\\s+(?P<Tipo>[A-Z]+)\\s+(?P<Detalles>.*?)(?:\\s+INTO\\s+|FROM\\s+)(?P<Tabla>\\w+)(?:.*?\\s+WHERE\\s+(?P<Condicion>.*))?`\n| line_format \"{{ .Tipo }},{{ .Tabla }},{{ .Condicion }},{{ .Detalles }}\"\n"
    }
   ]
  },
  {
   "title": "Consultas INSERT",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"mysql\",type=\"general\"} |~ \"Query\\\\s+INSERT\"\n| regexp `INSERT INTO (?P<Tabla>\\w+)\\s*\\((?P<Campos>[^)]+)\\)\\s+VALUES\\s*\\((?P<Valores>[^)]+)\\)`\n| line_format \"{{ .Tabla }}, Campos: {{ .Campos }}, Valores: {{ .Valores }}\"\n"
    }
   ]
  },
  {
   "title": "Consultas por segundo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "rate({job=\"mysql\"} |= \"Query\" [1m])"
    }
   ]
  },
  {
   "title": "Top 10 IPs por número de consultas",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"apache\", type=\"error\"} |= \"[HONEYX]\""
    }
   ]
  },
  {
   "title": "Intentos de inicio de sesión fallidos",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"mysql\"} |= \"Access denied\""
    }
   ]
  }
 ]
}